#pragma once

#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
//#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
//#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
//#define RGB_MATRIX_STARTUP_VAL  32

